# MoveIt uses this configuration for controller management
ros_control_namespace: /fairino3_v6

moveit_controller_manager: moveit_ros_control_interface/Ros2ControlManager

moveit_ros_control_interface:
  controller_names:
    - fairino3_v6/fairino3_moveit_controller

  fairino3_moveit_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6