# This config file is used by ros2_control
/fairino3_v6/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    fairino3_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gpio_controller:
      type: fairino_hardware/GPIOController

/fairino3_v6/fairino3_controller:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: true

/fairino3_v6/gpio_controller:
  ros__parameters:
    inputs:
     - tool_IO/AI0
     - tool_IO/DI0-7
     - controller_IO/AI0
     - controller_IO/AI1
     - controller_IO/DI0-15
    outputs:
     - tool_IO/AO0
     - tool_IO/DO0-7
     - controller_IO/AO0
     - controller_IO/AO1
     - controller_IO/DO0-15